### ISSUE TITLE
Bei Postleitzahlen, die mit "0" beginnen, wird die führende "0" entfern, ist aber dann im Suchfeld doch wieder benötigt.

### ISSUE THREAD

**Issue by dreirund** [timosystems/nachbarschaft.care#1]
* In der Karte wird bei Postleitzahlen, die mit `0` beginnen, die führende `0` entfernt. S. Bild 1.
* Wenn man sich zu solch einem PLZ-Bereich durchklickt und dann auf "Suchen" klickt, kommt kein Ergebnis. S. Bild 2.
* Es ist _manuell_ die führende `0` wieder hinzuzufügen. S. Bild 3.

Lösung sollte sein:
Führende `0` von Anfang an berücksichtigen!

---

Bild 1:  
![PLZ ohne führende 0](https://i.imgur.com/qyINhYI.png "PLZ ohne führende 0")

---

Bild 2:  
![Im Suchfeld wurde automatisch die PLZ ohne führende 0 eingetragen](https://i.imgur.com/BwqF940.png "Im Suchfeld wurde automatisch die PLZ ohne führende 0 eingetragen")

---

Bild 3:  
![Suchergebnis nur, wenn manuell die 0 wieder zugefügt wird](https://i.imgur.com/0L2zmN2.png "Suchergebnis nur, wenn manuell die 0 wieder zugefügt wird")

---

**Comment by timosystems** [comment]
Konnte den Fehler nachvollziehen und bereits die Ursache identifizieren: Das PLZ Feld in der Datenbank ist auf "integer" gestellt und schneidet daher die führende "0" ab. Werde das am Montag beheben. Vielen Dank!

**Comment by timosystems** [comment]
OK, der Fehler sollte nun behoben sein, wenn auch quick&dirty
