### ISSUE TITLE
Suche nur für eine konkrete PLZ möglich. Sollte sein: Für PLZ-Bereiche, oder für "Kartenausschnitt".

### ISSUE THREAD

**Issue by dreirund** [timosystems/nachbarschaft.care#2]
Momentan lässt sich nur für eine konkrete PLZ suchen. Das ist oftmals schlecht. Z.B.

* Wenig/ keine Angebote in genau dieser PLZ,
* wohnhaft an Grenze zwischen PLZen,
* Arbeit und Wohnung und weg dazwischem wo Hilfe angeboten werden kann,
* Mobil in bestimmtem Bereicht,
* ...

Es soltle die Möglichkeit geben, sowohl einen PLZ-Bereich zur Suche anzugeben (PLZ von ... bis, oder als Wildcard, z.B. `01*` oder, für Profis, `01[1-3]*`; habe absichtlich nicht regular expressions vorgeschlagen weil da sonst zwangsweise das Verankern am Stringbeginn mit `^` nötig wäre).

**Comment by timosystems** [comment]
Aus Performancegründen (schau die mal die Tabellen für PLZ Daten in der SQL Datei an) wird das nicht komplett frei definierbar sein, aber ich denke, ab der 3ten, 4ten oder 5ten Stelle PLZ stelle sollten Wildcards möglich sein. Ich werde schauen, dass ich das im laufe der kommenden Woche umsetze.

**Comment by timosystems** [comment]
Aufgrund mangelnder Nutzung der Software und geplanter Abschaltung und (personenbezogener) Datenlöschung mit abzusehendem Übergang in den Endemie-Zustand wird dieses Projekt von mir nicht mehr aktiv weiterentwickelt.
