### ISSUE TITLE
Bei der Suche zoomt die Karte immer wieder auf den Ausgangszustand zurück.

### ISSUE THREAD

**Issue by dreirund** [timosystems/nachbarschaft.care#3]
1. Ich zoome auf `1109`,
2. Ich führe eine Suche für `01109` durch (\[[was _mit_ `0` gemacht werden muss](/timosystems/nachbarschaft.care/issues/1)\]),
3. die Karte zeigt wieder gesamt Deutschland.

Es sollte die Karte eigentlich da bleiben, wo man sie vorher hin eingestellt hat.

Auch wäre es sinnvoll, wenn das "Suchfenster" im Vergleich zum "Kartenteil" in der Größe veränderbar wäre, aber das ist Grafik-Bonus.

**Comment by timosystems** [comment]
Hier scheint derselbe Bug verantwortlich zu sein, wie bei #1

**Comment by timosystems** [comment]
Wird geschlossen, da Duplikat ebenfalls geschlossen.
