### ISSUE TITLE
Mastodon account for this project

### ISSUE THREAD

**Issue by linux-lukas** [timosystems/nachbarschaft.care#6]
Would a Mastodon account for this project be possible?

**Comment by timosystems** [comment]
Hi @Lukas2112  sorry for the late reply. sure i can set one up. do you have a specific server in mind bc i never used mastodon so far.

**Comment by linux-lukas** [comment]
All good, thanks for your response. I could imagine that maybe social.tchncs.de could be a good place to start. Otherwise, maybe choose a smaller Mastodon instance, perhaps mastodon.technology or a regional one?

**Comment by timosystems** [comment]
thanks, if i continue this project then i will set one up
